### ISSUE TITLE
Error when using react.js as template engine

### ISSUE THREAD

**Issue by jephjohnson** [keystonejs/keystone-email#12]
I keep getting the following error when using react as my engine.
"Error: Could not load engine ([object Object]). Please make sure you have installed the package in your project."

new Email('test-email.jsx', {
  engine: require('react'),
}).send();

**Comment by w01fgang** [comment]
@jephjohnson React itself is not an engine.
Maybe you can try to use [express engine for react](https://github.com/magalhas/express-react-engine)

**Comment by jephjohnson** [comment]
@w01fgang - doh, that solved it
