### ISSUE TITLE
transporter not working?

### ISSUE THREAD

**Issue by johnnyluu** [keystonejs/keystone-email#24]
This is my code for testing the email module: 
```
new keystone.Email(
      'submission-approval', {
        transport: 'nodemailer'
      }).send({ first_name: 'Jonny', isApproved: isApproved }, {
      // apiKey: process.env.MANDRILL_API_KEY,
      nodemailerConfig: smtpConfig,
      to: 'johnnyluuu@gmail.com',
      from: 'jonny@romeodigital.com.au',
      subject: 'Test email'
    }, function (err, result) {
      if (err) {
        console.error('error:\n', err);
      } else {
        console.log('success:\n', result);
      }
 });
```
Doesn't matter what I put in as transporter 'mandrill', 'nodemailer', or 'mailgun', the result I get is always
```
 success [ { email: 'johnnyluuu@gmail.com',
    status: 'rejected',
    _id: '5b872de58d7546018bf691db2d0dc93c',
    reject_reason: 'unsigned' } ]
```
Which is the same response I got from mandrill-api because the domain I'm using is yet to be verified. But why would nodemailer and mailgun give me the same error?

**Comment by Noviny** [comment]
I suspect you've fallen prey to this problem:

http://stackoverflow.com/questions/38355344/mandrill-reject-reasonunsigned

Closing for now. Please feel free to reopen if this doesn't resolve it.
