### ISSUE TITLE
Integration with Nodemailer

### ISSUE THREAD

**Issue by ttsirkia** [keystonejs/keystone-email#4]
It seems that this project will implement new transportation mechanisms to send mail. There is already `nodemailer` npm package that has many [transportation mechanisms](http://nodemailer.com/2-0-0-beta/setup-transporter/) (including simple `sendmail`, Mandrill and various 3rd party libraries).

Would it be meaningful to use Nodemailer and its transporters instead of rewriting those in this project?

**Comment by stennie** [comment]
Fixed via PR #10
